services:
  db:
    image: 'postgres:16.2'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  
  backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/development/backend.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  
  frontend:
    build:
      context: .
      dockerfile: docker/development/frontend.Dockerfile
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: yarn dev --port 3001 --host 0.0.0.0
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres:
  node_modules: